# Generated by Django 4.2.7 on 2023-11-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='data_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='data_saida',
            field=models.DateField(),
        ),
    ]
