# Generated by Django 4.2.7 on 2023-11-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carro_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
            preserve_default=False,
        ),
    ]
