# Generated by Django 4.2.5 on 2023-11-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.carro'),
            preserve_default=False,
        ),
    ]
