# Generated by Django 4.2.5 on 2023-09-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areasaber_avaliacao_curso_disciplina_frequencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='instituição',
            new_name='instituicao',
        ),
    ]
