# Generated by Django 4.2.5 on 2023-09-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caregoria',
            new_name='Categoria',
        ),
    ]
