# Generated by Django 4.2.7 on 2023-11-07 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pessoa_idade_alter_carro_data_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.modelo'),
            preserve_default=False,
        ),
    ]
