# Generated by Django 4.2.5 on 2023-11-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vagas_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
            preserve_default=False,
        ),
    ]
